### ISSUE TITLE
Can not compile mormot2tests: File not found: 'FastMM4.dcu'

### ISSUE THREAD

**Issue by PeterAdam** [synopse/mORMot2#184]
I have installed (not found the exact version yet, but downloaded the archive in a zip format from GitHub today) according to the included readme.md, but can not compile mormot2tests.pas to Delphi 7.

[Fatal Error] mormot2tests.dpr(60): File not found: 'FastMM4.dcu'

Is it a required 3rd party library? mORMot2\src\core\README.md says it contains mormot.core.fpcx64mm which is based on FastMM4.
However, mORMot2\src\mormot.defines.inc defines fastmm only for version  >= 18, while mORMot2\src\mormot.uses.inc defines it for version <= 17.

**Comment by synopse** [comment]
You can remove the FastMM4 reference in mormot.uses.inc for Delphi 7, by commenting the line.
But I would advice against it, because Delphi 7 MM is just dead slow in comparison.
On Delphi 7, we use the official FastMM4 library, as available e.g. in https://github.com/synopse/mORMot/tree/master/RTL7

Please use our forum for such discussion, not github.
