### ISSUE TITLE
修正UnicodeBufferToAnsi函数不支持中文问题

### ISSUE THREAD

**Issue by blue8228** [synopse/mORMot2#186]
src\core\mormot.core.unicode.pas src\core\mormot.core.unicode.pas

Unicode_WideToAnsi(Source, Dest, SourceChars, SourceChars, fCodePage));
--->>>
Unicode_WideToAnsi(Source, Dest, SourceChars, (SourceChars + 1) shl fAnsiCharShift, fCodePage));

**Comment by synopse** [comment]
On which OS ?
On which compiler ?

The +1 is not expected because it is up to the caller to add the trailing #0.
On Windows, it just calls WideCharToMultiByte() which requires the UTF-16 chars count, not the bytes count.
On Linux, it calls either Unicode2AnsiMoveProc() or ucnv_fromUChars() which also both requires the UTF-16 chars count.

So I don't understand your modifications.
Please use the synopse forum for discussion about this.

**Comment by synopse** [comment]
I guess the discussion continues at 
https://synopse.info/forum/viewtopic.php?id=6583
